// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsv8R7q8UwfqX8z64BQAdCiAzJew1m0Qw',
    appId: '1:531477574806:android:a42bfebec29090fab6beb7',
    messagingSenderId: '531477574806',
    projectId: 'tiktok-flutter-clone-1c93f',
    storageBucket: 'tiktok-flutter-clone-1c93f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBJV_kjyzjIdS5OzzIsEta5SwSF-BbeRI',
    appId: '1:531477574806:ios:dfaa34b82f7d6814b6beb7',
    messagingSenderId: '531477574806',
    projectId: 'tiktok-flutter-clone-1c93f',
    storageBucket: 'tiktok-flutter-clone-1c93f.appspot.com',
    iosClientId: '531477574806-m8oah252vj01un7fm1qun011vuon4c95.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokTutorial',
  );
}
